# Generated by Django 4.0.2 on 2022-02-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название источника')),
                ('link', models.URLField(unique=True, verbose_name='Адрес источника')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Подтверждение администратора')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, default='Читайте полный текст в источнике', null=True, verbose_name='Текст новости')),
                ('published', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дата публикации')),
                ('saved', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
                ('is_deleted', models.BooleanField(default=True, editable=False, verbose_name='Активность')),
                ('site', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='AllNews.site')),
                ('tags', models.ManyToManyField(to='AllNews.Tag')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published'],
                'unique_together': {('title', 'link')},
            },
        ),
    ]
